# Generated by Django 4.2.7 on 2023-11-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('tool', 'Tool')], max_length=20)),
                ('icon_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(default='없음')),
                ('tech_stacks', models.ManyToManyField(related_name='job_positions', to='main.techstack')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(default='없음', max_length=100)),
                ('job_positions', models.ManyToManyField(related_name='companies', to='main.jobposition')),
            ],
        ),
    ]
