# Generated by Django 4.2.7 on 2023-11-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="company", name="address",),
        migrations.AddField(
            model_name="company",
            name="sido",
            field=models.CharField(default="시도", max_length=50),
        ),
        migrations.AddField(
            model_name="company",
            name="sigg",
            field=models.CharField(default="시군구", max_length=50),
        ),
        migrations.AlterField(
            model_name="techstack",
            name="type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
