# Generated by Django 4.2.7 on 2023-11-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_company_address_company_sido_company_sigg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposition",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
