# Generated by Django 4.2.7 on 2023-11-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_jobposition_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company", name="name", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="company", name="sido", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="company", name="sigg", field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                fields=("name", "sido", "sigg"), name="unique fields for each company"
            ),
        ),
    ]
