# Generated by Django 4.2.7 on 2023-11-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_company_name_alter_company_sido_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="techstack", name="name", field=models.CharField(max_length=50),
        ),
    ]
