# Generated by Django 4.2.7 on 2023-11-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_techstack_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="company", name="job_positions",),
        migrations.RemoveField(model_name="jobposition", name="tech_stacks",),
        migrations.RemoveField(model_name="techstack", name="icon_url",),
        migrations.AddField(
            model_name="techstack",
            name="companies",
            field=models.ManyToManyField(related_name="tech_stacks", to="main.company"),
        ),
        migrations.AddField(
            model_name="techstack",
            name="job_positions",
            field=models.ManyToManyField(
                related_name="tech_stacks", to="main.jobposition"
            ),
        ),
    ]
