# Generated by Django 4.2.7 on 2023-11-11 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_company_job_positions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"parent": None},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.location",
                    ),
                ),
            ],
        ),
    ]
