# Generated by Django 4.2.7 on 2023-11-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_company_job_positions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
