# Generated by Django 4.2.7 on 2023-11-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_techstack_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
